hotelmanagement/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('',include('guest.urls')),
    path('',include('room.urls')),
    path("accounts/", include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('modd',views.Moddview.as_view(),name="modd"),
    path('', views.DashboardView.as_view(), name='dashboard'),
    path('reservations/', views.ReservationListView.as_view(), name='reservation_list'),
    path('reservation/create/', views.ReservationCreateView.as_view(), name='reservation_create'),
    path('reservation/<int:pk>/update', views.ReservationUpdateView.as_view(), name='reservation_update'),
    path('reservation/<int:pk>', views.ReservationDetailView.as_view(), name='reservation_detail'),
]

guest/models.py
# guest/models.py
from django.db import models

class Guest(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(unique=True)
    phone_number = models.CharField(max_length=15)
    government_id = models.CharField(max_length=15)
    address = models.TextField(max_length=200)
    def __str__(self):
        return f"{self.first_name} {self.last_name} {self.phone_number}"

main/models.py
from django.db import models
from django.urls import reverse


class Reservation(models.Model):
    room = models.ForeignKey('room.Room', on_delete=models.CASCADE)
    guest = models.ForeignKey('guest.Guest', on_delete=models.CASCADE)
    additional = models.TextField(null=True,blank=True)
    check_in_date = models.DateField()
    check_out_date = models.DateField()
    
    def get_absolute_url(self):
        return reverse('reservation_detail', args=[str(self.id)])
    def __str__(self):
        return f"{self.room.room_number} | form {self.check_in_date} to {self.check_out_date}"

room/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, time

class Room(models.Model):
    room_number = models.CharField(max_length=10, unique=True)
    room_type = models.CharField(max_length=50)
    price_per_night = models.DecimalField(max_digits=8, decimal_places=2)

    def is_booked_now(self):
        now = timezone.now()
        reservations = self.reservation_set.all()
        return any(
            timezone.make_aware(timezone.datetime.combine(reservation.check_in_date, time(12, 0, 0)), timezone.get_current_timezone()) <= now <=
            timezone.make_aware(timezone.datetime.combine(reservation.check_out_date, time(12, 0, 0)), timezone.get_current_timezone())
            for reservation in reservations
        )
    def __str__(self):
        return self.room_number

main/views.py
from django.shortcuts import render
from django.views import View
from django.views.generic import CreateView, UpdateView, ListView
from django.urls import reverse_lazy
from .models import Reservation
from django.views.generic import DetailView
from django import forms
from django.contrib.auth.mixins import LoginRequiredMixin
from room.models import Room
from guest.models import Guest

class CustomReservationForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = '__all__'
        widgets = {
            'check_in_date': forms.DateInput(attrs={'type': 'date'}),
            'check_out_date': forms.DateInput(attrs={'type': 'date'}),
        }

class Moddview(View):
    def get(self,request):
        return render(request,'modd.html')

class DashboardView(View):
    def get(self, request):
        total_rooms = Room.objects.all().count()
        total_guests = Guest.objects.all().count()
        total_reservations = Reservation.objects.all().count()
        context = {
            'total_rooms': total_rooms,
            'total_guests': total_guests,
            'total_reservations': total_reservations,
        }
        return render(request, 'dashboard.html', context)

class ReservationCreateView(LoginRequiredMixin, CreateView):
    model = Reservation
    template_name = "form.html"
    form_class = CustomReservationForm

    def get_initial(self):
        initial = super().get_initial()
        guest_id = self.request.GET.get('guest_id')
        if guest_id:
            initial['guest'] = guest_id
        return initial

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Create Reservation"
        return context

    def form_valid(self, form):
        room = form.cleaned_data['room']
        check_in_date = form.cleaned_data['check_in_date']
        check_out_date = form.cleaned_data['check_out_date']
        existing_reservations = Reservation.objects.filter(
            room=room,
            check_in_date__lt=check_out_date,
            check_out_date__gt=check_in_date
        )
        if existing_reservations.exists():
            form.add_error('room', 'This room is already booked for the selected dates.')
            return self.form_invalid(form)
        else:
            return super().form_valid(form)




class ReservationUpdateView(LoginRequiredMixin, UpdateView):
    model = Reservation
    template_name = "form.html"
    form_class = CustomReservationForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Update Reservation"
        return context
    def form_valid(self, form):
        room = form.cleaned_data['room']
        check_in_date = form.cleaned_data['check_in_date']
        check_out_date = form.cleaned_data['check_out_date']
        existing_reservations = Reservation.objects.filter(
            room=room,
            check_in_date__lt=check_out_date,
            check_out_date__gt=check_in_date
        )
        if existing_reservations.exists():
            form.add_error('room', 'This room is already booked for the selected dates.')
            return self.form_invalid(form)
        else:
            return super().form_valid(form)    
    

class ReservationDetailView(LoginRequiredMixin, DetailView):
    model = Reservation
    template_name = "reservation_detail.html"

class ReservationListView(LoginRequiredMixin, ListView):
    model = Reservation
    paginate_by = 10
    context_object_name = "reservations"
    template_name = "reservation_list.html"
    def get_queryset(self):
        # Get the room number from the query parameters
        room_number = self.request.GET.get('room_number')

        # Filter reservations for the specified room number
        if room_number:
            return Reservation.objects.filter(room__room_number=int(room_number)).order_by('-id')
        else:
            return Reservation.objects.all().order_by('-id')

main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock title %} | Hotel Management</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
    <header>
        <h1>HOTELHUB</h1>
    </header>

<nav>
    <ul>
        <li><a href="{% url 'dashboard' %}">Dashboard</a></li>
        {% if user.is_authenticated %}
        <li><a href="{% url 'room_list' %}">Room List</a></li>
        <li><a href="{% url 'guest_list' %}">Guest List</a></li>
        <li><a href="{% url 'reservation_list' %}">reservation List</a></li>
        <li><a href="{% url 'room_create' %}">Create Room</a></li>
        <li><a href="{% url 'guest_create' %}">Create Guest</a></li>
        <li><a href="{% url 'reservation_create' %}">Create Reservation</a></li>
        <li><a href="{% url 'profile' %}">Profile</a></li>
        <li><a href="{% url 'logout'%}?next={% url 'login' %}">Logout</a></li>
        {% else %}
        <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
        {% endif %}
    </ul>
</nav>


    <main>
        {% block content %}
        {% endblock %}
        {% block pagination %}
    {% if is_paginated %}
        <ul class="pagination">

            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="{{ request.path }}?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="{{ request.path }}?page={{ page_obj.previous_page_number }}">
                        {{ page_obj.previous_page_number }}
                    </a>
                </li>
            {% endif %}

            <li class="page-item">
                <a class="page-link active" href="#">
                    {{ page_obj.number }}
                </a>
            </li>

            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="{{ request.path }}?page={{ page_obj.next_page_number }}">
                        {{ page_obj.next_page_number }}
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="{{ request.path }}?page={{ page_obj.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            {% endif %}

        </ul>
    {% endif %}
{% endblock %}

    </main>

    <footer>
        &#169; created by <a class="linky" href="{% url 'modd' %}">MODD</a>
    </footer>
</body>
</html>

main/templates/dashboard.html
{% extends 'base.html' %}
{% block title %}Dashboard{% endblock title %}
{% block content %}
  <h2 class="titlex">Welcome to the HotelHub</h2>

  <div class="dashboard">
    <div class="card">
        <h2 class="titlex">Rooms</h2>
        <p>{{ total_rooms }}</p>
    </div>

    <div class="card">
        <h2 class="titlex">Total Guests</h2>
        <p>{{ total_guests }}</p>
    </div>

    <div class="card">
        <h2 class="titlex"> Total Reservations </h2>
        <p>{{ total_reservations }}</p>
    </div>
</div>

{% endblock %}

main/templates/modd.html
{% extends 'base.html' %}

{% block title %}SUPERUSER{% endblock title %}

{% block content %}
<h2 class="titlex">About</h2>
<p>HOTELHUB is a Hotel Management System created by MODD.<br><hr>
<h3 class="titlex">Contact</h3>
<p>Mail: <a href="mailto:immodded@proton.me" class="linky">immodded@proton.me</a>



    {% endblock content %}

main/templates/reservation_detail.html
{% extends 'base.html' %}

{% block title %}Reservation Detail{% endblock %}


{% block content %}
  <h2 class="titlex">Reservation Detail</h2>
  <p>Room: {{ reservation.room.room_number }}</p>
  <p>Guest: {{ reservation.guest.first_name }}</p>
  <p>Check-in Date: {{ reservation.check_in_date }}</p>
  <p>Check-out Date: {{ reservation.check_out_date }}</p>
  <p>Additional Details : {{ reservation.additional|linebreaks }}</p>
  <a class="linkx" href="{% url 'reservation_update' reservation.id %}">Update</a>
  {% endblock %}

main/templates/reservation_list.html
{% extends 'base.html' %}

{% block title %}Reservation List{% endblock %}


{% block content %}
  <h2 class="titlex">Reservations</h2>
  <table>
    <thead>
      <tr>
      <th>Room No</th>
      <th>Guest</th>
      <th>Check In</th>
      <th>Check out</th>
      </tr>
    </thead>
    <tbody>
      {% for reservation in reservations %}
      <tr>
      <td><a class="linky" href="{% url 'reservation_detail' reservation.id %}">{{ reservation.room.room_number }} </a> </td>
      <td><a class="linky" href="{% url 'guest_detail' reservation.guest.id %}">{{ reservation.guest.first_name }} {{ reservation.guest.last_name }}</a></td>
      <td><a class="linky" href="{% url 'reservation_detail' reservation.id %}">{{ reservation.check_in_date }}</a></td>
      <td><a class="linky" href="{% url 'reservation_detail' reservation.id %}">{{ reservation.check_out_date }}</a></td>
      </tr>
      {% empty %}
      <p>No Record found! <a href="{% url 'reservation_create' %}" class="linky">Create Reservation </a></p>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}